set quiet

static_dir := "../backend/priv/static"

[private]
default:
    just --list

# build frontend and send files to the backend
[group("dev")]
build: install
    npm run build --no-fund
    mv dist/assets/*.css dist/assets/client.css
    mv dist/assets/*.js dist/assets/client.js
    mkdir -p  {{ static_dir }}
    mv dist/* {{ static_dir }}

# download project dependencies
[group("dev")]
install:
    npm install
