set quiet

[private]
default:
    just --list

# Build frontend and send files to the backend
build:
    npm run build --no-fund
    mv dist/assets/*.css dist/assets/client.css
    mv dist/assets/*.js dist/assets/client.js
    mkdir ../backend/priv/static || true
    mv dist/* ../backend/priv/static
