mod frontend "../frontend/justfile"

set quiet

# Server
export DATABASE_URL := "postgres://aluno:123@localhost:5432/senac"
export SECRET_KEY := "senac"
database_container_name := "server_postgres"
docker_compose := "docker compose -f ../docker-compose.yaml"

#   Erlang-related variables
node_name := "wibble@127.0.0.1"
erlang_cookie := "wibble"

[private]
default:
    just --list

# Run unit tests
[group("dev")]
test: require-database
    gleam test

# Build documentation
[group("dev")]
build-documentation: build
    echo {{ MAGENTA }}"  Building documentation.."{{ NORMAL }}
    gleam docs build
    echo {{ GREEN }}"  Click the link to open it in your browser."{{ NORMAL }}

# Run application
[group("dev")]
run: require-database build
    ERL_FLAGS="-name {{ node_name }} -setcookie {{ erlang_cookie }}" gleam run

# Open erlang observer
[group("dev")]
observer observer_node_name="wobble@127.0.0.1": require-server
    erl -name {{ observer_node_name }} -setcookie {{ erlang_cookie }} \
      -hidden -run observer start {{ node_name }}

# Watch and run application
[group("dev")]
watch-run debounce="500ms":
    watchexec --restart --verbose --wrap-process=session \
       --stop-signal SIGTERM --exts gleam --debounce {{ debounce }} --clear \
       --watch src/ -- just run

# Watch and run unit tests
[group("dev")]
watch-test debounce="500ms":
    watchexec --restart --verbose --wrap-process=session \
       --stop-signal SIGTERM --exts gleam --debounce {{ debounce }} --clear \
       --watch src/ --watch test/ -- just test

# Build container
[group("docker")]
build-container:
    {{ docker_compose }} build

# Build backend
[group("dev")]
build:
    gleam build

# Build the frontend and copy the assets into priv/static
[group("dev")]
build-frontend:
    rm -rf priv/static
    just frontend::build

# Start containers
[group("docker")]
up:
    {{ docker_compose }} up -d

# Stop containers
[confirm("Stop containers and clean resources? [y/N]")]
[group("docker")]
down:
    {{ docker_compose }} down -v

# Generate SQL queries
[group("dev")]
generate-sql: require-database
    echo {{ GREEN }}"  Generating SQL queries"{{ NORMAL }}
    gleam run -m squirrel

# Start the database container
[group("database")]
start-database:
    echo {{ YELLOW }}"󱎫  Starting PostgreSQL..."{{ NORMAL }}
    {{ docker_compose }} up -d postgres
    timeout 30 bash -c 'until pg_isready -q -h localhost -p 5432 -U aluno -d senac; do sleep 0.2; done' \
    || ( echo {{ YELLOW }}"PostgreSQL did not become ready in 30s"{{ NORMAL }} && exit 1 )
    echo {{ GREEN }}"  PostgreSQL is now running"{{ NORMAL }}

# Restart the database container with a fresh database
[group("database")]
restart-database: stop-database && start-database
    echo {{ GREEN }}"󱎫  Rebuilt the PostgreSQL database"{{ NORMAL }}

# Stop the database container
[group("database")]
stop-database:
    docker rm -f -v {{ database_container_name }} || true
    echo {{ GREEN }}"  Stopped the database container"{{ NORMAL }}

# Check if the database is active
[no-exit-message]
[private]
require-database:
    pg_isready -q -h localhost -p 5432 -U aluno -d senac \
    || ( echo {{ YELLOW }}"  Database is not running, starting it"{{ NORMAL }} \
    && just start-database )

# Check if the server is active
[no-exit-message]
[private]
require-server:
    curl -sf http://localhost:8000/api/healthcheck \
    || ( echo {{ YELLOW }}"  HTTP Server needs to be running"{{ NORMAL }} \
    && just --usage run && exit 1 )
