/** Os 27 estados brasileiros (UF + nome completo). */
export const UFS = [
  { valor: 'AC', rotulo: 'AC — Acre' },
  { valor: 'AL', rotulo: 'AL — Alagoas' },
  { valor: 'AP', rotulo: 'AP — Amapá' },
  { valor: 'AM', rotulo: 'AM — Amazonas' },
  { valor: 'BA', rotulo: 'BA — Bahia' },
  { valor: 'CE', rotulo: 'CE — Ceará' },
  { valor: 'DF', rotulo: 'DF — Distrito Federal' },
  { valor: 'ES', rotulo: 'ES — Espírito Santo' },
  { valor: 'GO', rotulo: 'GO — Goiás' },
  { valor: 'MA', rotulo: 'MA — Maranhão' },
  { valor: 'MT', rotulo: 'MT — Mato Grosso' },
  { valor: 'MS', rotulo: 'MS — Mato Grosso do Sul' },
  { valor: 'MG', rotulo: 'MG — Minas Gerais' },
  { valor: 'PA', rotulo: 'PA — Pará' },
  { valor: 'PB', rotulo: 'PB — Paraíba' },
  { valor: 'PR', rotulo: 'PR — Paraná' },
  { valor: 'PE', rotulo: 'PE — Pernambuco' },
  { valor: 'PI', rotulo: 'PI — Piauí' },
  { valor: 'RJ', rotulo: 'RJ — Rio de Janeiro' },
  { valor: 'RN', rotulo: 'RN — Rio Grande do Norte' },
  { valor: 'RS', rotulo: 'RS — Rio Grande do Sul' },
  { valor: 'RO', rotulo: 'RO — Rondônia' },
  { valor: 'RR', rotulo: 'RR — Roraima' },
  { valor: 'SC', rotulo: 'SC — Santa Catarina' },
  { valor: 'SP', rotulo: 'SP — São Paulo' },
  { valor: 'SE', rotulo: 'SE — Sergipe' },
  { valor: 'TO', rotulo: 'TO — Tocantins' },
]
